// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZvEptH9tH0usHM6Zsuuwe1_6niUlRxg0',
    appId: '1:315587143368:web:3a0d04aa43c3b87eb867fd',
    messagingSenderId: '315587143368',
    projectId: 'ethos-6c24a',
    authDomain: 'ethos-6c24a.firebaseapp.com',
    storageBucket: 'ethos-6c24a.firebasestorage.app',
    measurementId: 'G-E9W1LQKNPC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBr3JnYn7qKgS5Ly67JsOgx4TKFpRv-M9g',
    appId: '1:315587143368:android:677f3902a31b052bb867fd',
    messagingSenderId: '315587143368',
    projectId: 'ethos-6c24a',
    storageBucket: 'ethos-6c24a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABcbKWrv6r8VpLxroK37fyNyiSKIHM0ok',
    appId: '1:315587143368:ios:fc94a5c119af8c0db867fd',
    messagingSenderId: '315587143368',
    projectId: 'ethos-6c24a',
    storageBucket: 'ethos-6c24a.firebasestorage.app',
    iosBundleId: 'com.example.ethos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABcbKWrv6r8VpLxroK37fyNyiSKIHM0ok',
    appId: '1:315587143368:ios:fc94a5c119af8c0db867fd',
    messagingSenderId: '315587143368',
    projectId: 'ethos-6c24a',
    storageBucket: 'ethos-6c24a.firebasestorage.app',
    iosBundleId: 'com.example.ethos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZvEptH9tH0usHM6Zsuuwe1_6niUlRxg0',
    appId: '1:315587143368:web:9cd5b821494cbed7b867fd',
    messagingSenderId: '315587143368',
    projectId: 'ethos-6c24a',
    authDomain: 'ethos-6c24a.firebaseapp.com',
    storageBucket: 'ethos-6c24a.firebasestorage.app',
    measurementId: 'G-B4JRD03N6N',
  );
}
